connectedin/connectedin/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('perfis.urls')),
    url(r'^', include('usuarios.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

connectedin/perfis/urls.py
from django.conf.urls import patterns, url
from perfis import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^perfis/(?P<perfil_id>\d+)$', views.exibir, name='exibir'),
    url(r'^perfis/(?P<perfil_id>\d+)/convidar$', views.convidar, name='convidar'),
    url(r'^convites/(?P<convite_id>\d+)/aceitar$', views.aceitar, name='conectar'),
)

connectedin/usuarios/urls.py
from django.conf.urls import patterns, url
    
from usuarios.views import RegistrarUsuarioView

urlpatterns = patterns('',
    url(r'^registrar/$', RegistrarUsuarioView.as_view(), name="registrar"),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name':'usuarios/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', {'login_url':'/login/'}, name='logout'),
)

connectedin/perfis/models.py
from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
    
    nome = models.CharField(max_length=255)
    telefone = models.CharField(max_length=15, null=True)
    nome_empresa = models.CharField(max_length=255, null=True)

    contatos = models.ManyToManyField('self')

    usuario = models.OneToOneField(User, related_name="perfil")

    @property
    def email(self):
        return self.usuario.email

    def convida(self, perfil_convidado):
        if not self.is_convidado(perfil_convidado) and perfil_convidado != self:
            Convite(solicitante=self, convidado=perfil_convidado).save()

    def is_convidado(self, perfil):
        
        convites_feitos = self.convites_feitos.filter(convidado__id=perfil.id).exists()
        convites_recebidos = self.convites_recebidos.filter(solicitante__id=perfil.id).exists()

        return  convites_feitos or convites_recebidos

class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, related_name="convites_feitos")
    convidado = models.ForeignKey(Perfil, related_name="convites_recebidos")

    def aceita(self):
        self.convidado.contatos.add(self.solicitante)
        self.delete()

connectedin/usuarios/models.py
from django.db import models

# Create your models here.

connectedin/usuarios/forms.py
from django import forms

from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):
    
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=False)
    senha = forms.CharField(required=False)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def add_error(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.util.ErrorList())
        errors.append(message)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.add_error("Por favor, verifique os dados informados")
            valid = False

        user_exists = User.objects.filter(username=self.data['email']).exists()

        if user_exists:
            self.add_error("Usuario ja existente")
            valid = False

        return valid

connectedin/perfis/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import RequestContext, loader
from perfis.models import Perfil, Convite

from django.http.response import HttpResponseRedirect

from django.core.urlresolvers import reverse

from django.http import Http404

from django.contrib.auth.decorators import login_required

@login_required
def index(request):
	return render(request, 'perfis/index.html', 
					{"perfis":Perfil.objects.all(), 
					 "perfil_logado":__get_perfil_logado(request)})

@login_required
def exibir(request, perfil_id):
    perfil = get_object_or_404(Perfil, id=perfil_id)

    perfil_logado = __get_perfil_logado(request)
    is_conectado = perfil in perfil_logado.contatos.all()
    
    return render(request, 'perfis/perfil.html',{'perfil': perfil, 'is_conectado': is_conectado})

@login_required
def convidar(request, perfil_id):
        
    perfil_a_convidar = get_object_or_404(Perfil, id=perfil_id)

    perfil_logado = __get_perfil_logado(request)

    perfil_logado.convida(perfil_a_convidar)

    return HttpResponseRedirect( reverse('index') )

@login_required
def aceitar(request, convite_id):
    convite = get_object_or_404(Convite, id=convite_id)
    convite.aceita()
    return HttpResponseRedirect( reverse('index') )

def __get_perfil_logado(request):
        return request.user.perfil

connectedin/usuarios/views.py
from django.shortcuts import render

from django.views.generic.base import View

from django.shortcuts import render

from usuarios.forms import RegistrarUsuarioForm
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from perfis.models import Perfil

from django.core.urlresolvers import reverse

class RegistrarUsuarioView(View):
    
    template_name = 'usuarios/registrar.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        form = RegistrarUsuarioForm(request.POST)
        
        if form.is_valid():

            dados_form = form.data
            
            usuario = User.objects.create_user(dados_form['email'], dados_form['email'], dados_form['senha'])            
        
            perfil = Perfil(nome=dados_form['nome'], 
                            email=dados_form['email'], 
                            telefone=dados_form['telefone'],
                            nome_empresa=dados_form['nome_empresa'],
                            usuario=usuario)

            perfil.save()

            return HttpResponseRedirect( reverse('login') )

        return render(request, self.template_name, {'form': form})

connectedin/perfis/templates/perfis/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block header %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>ConnectedIn</title>

        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "styles/main.css" %}" rel="stylesheet">
    {% endblock %}
  </head>
  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li class=""><a href="{% url 'index' %}">{{user.perfil.nome}}</a></li>
          <li class=""><a href="/logout/">Logout</a></li>
        </ul>
        <h3 class="text-muted">ConnectedIn</h3>
      </div>

      <div class="row content">
            {% block body %}

            {% endblock %}        
      </div>
    </div>
    <script src="{% static "scripts/vendor/bootstrap-min.js" %}"></script>
  </body>
</html>

connectedin/perfis/templates/perfis/index.html
{% extends "perfis/base.html" %}

{% block body %}

<div class="col-lg-12">

    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Todos os Perfis</strong>
        </div>
        {% if perfis %}
            <ul class="list-group">
                {% for perfil in perfis %}
                    <a href="{% url 'exibir' perfil.id %}" class="list-group-item">{{ perfil.nome }} // {{ perfil.email }}</a>
                {% endfor %}
            </ul>
        {% else %}
            <div class="panel-body">
                <p>Nenhum Perfil encontrado</p>
            </div>
        {% endif %}
    </div>

    <div class="panel panel-default">
        {% with total_de_convites=perfil_logado.convites_recebidos.count %}
            {% if total_de_convites %}
                <div class="panel-heading">
                        <strong>Você tem {{total_de_convites}} convite{{ total_de_convites|pluralize }} aguardando aprovação</strong>
                </div>
                <ul class="list-group">
                    {% for convite in perfil_logado.convites_recebidos.all %}
                        <li class="list-group-item">
                                {{ convite.solicitante.nome }} 
                                <a href="{% url 'conectar' convite.id %}" class="pull-right">aceitar</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="panel-body">
                    <p>Nenhum convite recebido :(</p>
                </div>
            {% endif %}
        {% endwith %}
    </div>

    <div class="panel panel-default">
        {% with total_de_contatos=perfil_logado.contatos.count %}
            {% if total_de_contatos %}
                <div class="panel-heading">
                        <strong>Você tem {{total_de_contatos}} contato{{ total_de_contatos|pluralize }}</strong>
                </div>
                <ul class="list-group">
                {% for contato in perfil_logado.contatos.all %}
                    <a href="{% url 'exibir' contato.id %}" class="list-group-item">{{ contato.nome }} // {{ contato.email }}</a>
                {% endfor %}
            </ul>
            {% else %}
                <div class="panel-body">
                    <p>Você não possui contatos no momento :(</p>
                </div>
            {% endif %}
        {% endwith %}
    </div>

</div>

{% endblock %}

connectedin/perfis/templates/perfis/perfil.html
{% extends "perfis/base.html" %}

{% block body %}

<div class="row">
    <div class="col-lg-12">
        <h2 style="margin-top:0">{{perfil.nome}}</h2>
        <address>
          <strong>{{perfil.nome_empresa}}</strong><br>
          <abbr title="Telefone">Tel:</abbr> {{perfil.telefone}}<br>
          <a href="mailto:{{profile.email}}">{{profile.email}}</a>
        </address>
        {% if is_conectado %}
        	<div class="well well-sm">Vocês estão conectados!</div>
	    {% else %}
	        <a href="{% url 'convidar' perfil.id %}"  class="btn btn-success" role="button">convidar</a>
	    {% endif %}
    </div>
</div>

{% endblock %}

connectedin/usuarios/templates/usuarios/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>ConnectedIn</title>
      
    <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "styles/signin.css" %}" rel="stylesheet">

  </head>

  <body>
    <div class="container">
      {% block body %}

      {% endblock %} 
    </div>  
     <script src="{% static "scripts/vendor/bootstrap-min.js" %}"></script>
  </body>
</html>

connectedin/usuarios/templates/usuarios/login.html
{% extends "usuarios/base.html" %}

{% block body %}
          
    <form class="form-signin" role="form" action="{% url 'django.contrib.auth.views.login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>
                
        <input type="text" id="id_username" name="username" class="form-control" placeholder="Email" required autofocus>
                
        <input type="password" id="id_passowrd" name="password" class="form-control" placeholder="Senha" required>
                
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>
                
        <input type="hidden" name="next" value="{{ next }}" />
                
        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Por favor, verifique o Email e/ou Senha informados
          </div>
        {% endif %}

        <a href="{% url 'registrar' %}">registre-se</a>
    </form>

{% endblock %}

connectedin/usuarios/templates/usuarios/registrar.html
{% extends "usuarios/base.html" %}

{% block body %}
      
      <form class="form-signin" role="form" action="{% url 'registrar' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Crie seu usuário</h2>

        <input type="text" id="id_email" name="email" value="{{form.data.email}}" class="form-control" placeholder="Email *" required autofocus>
        
        <input type="password" id="id_senha" name="senha" value="{{form.data.senha}}" class="form-control"  placeholder="Senha *" required>

        <hr />

        <input type="text" id="id_nome" name="nome" value="{{form.data.nome}}" class="form-control" placeholder="Nome *" required >

        <input type="text" id="id_telefone" name="telefone" value="{{form.data.telefone}}" class="form-control" placeholder="Telefone">

        <input type="text" id="id_nome_empresa" name="nome_empresa" value="{{form.data.nome_empresa}}" class="form-control" placeholder="Empresa">

        <hr />

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>
        
        <hr />

        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{form.non_field_errors}}
          </div>
        {% endif %}

      </form>

{% endblock %}